puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'Hello World'
puts 'Enhanced'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
puts 'All work and no play makes Ruby sad'
